name: Build Tachyon

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  schedule:
    - cron: '7 1 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux/archlinux:latest
    strategy:
      fail-fast: true

    steps:
      - name: Get Shell Script
        uses: actions/checkout@v4

      - name: Check Kernel Version
        run: |
          export BUILD_ROOT="tachyon"
          bash build-kernel.sh --skip-if-released

      - name: Get base environment
        if: env.TACHYON_SKIP == 0
        run: |
          pacman -Syyu --noconfirm
          pacman -S github-cli --noconfirm

      - name: Upload Build Artifacts For AnyKernel3
        uses: actions/upload-artifact@v7
        if: env.TACHYON_SKIP == 0
        with:
          path: |
            ${{ env.TACHYON_PKG_DIR }}/${{ env.TACHYON_KERNEL_PKG }}
            ${{ env.TACHYON_PKG_DIR }}/${{ env.TACHYON_HEADERS_PKG }}
          archive: true

      - name: Set Release Variables
        if: env.TACHYON_SKIP == 0
        run: |
          NEW_TAG="${{ env.TACHYON_VERSION }}"
          TIME=$(date +"%Y-%m-%d %H:%M")

          echo "New tag: $NEW_TAG"
          echo "TIME=$TIME" >> $GITHUB_ENV
          echo "NEW_TAG=${NEW_TAG}" >> $GITHUB_ENV

      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v3
        if: env.TACHYON_SKIP == 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEW_TAG }}
          name: "Tachyon ${{ env.TIME }}"
          prerelease: false
          files: |
            ${{ env.TACHYON_PKG_DIR }}/${{ env.TACHYON_KERNEL_PKG }}
            ${{ env.TACHYON_PKG_DIR }}/${{ env.TACHYON_HEADERS_PKG }}
